######################################################################
# Automatically generated by qmake (2.01a) Mo. Apr 18 21:55:09 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
