######################################################################
# Automatically generated by qmake (2.01a) Mo. Apr 18 21:55:09 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp \
    specialList.cpp \
    StacksAndQueues.cpp \
    MappingAndHashing.cpp \
    person.cpp \
    Hashing01.cpp

HEADERS += \
    person.h
