######################################################################
# Automatically generated by qmake (2.01a) Fr. Apr 15 20:56:27 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += myclass.h
SOURCES += main.cpp
