######################################################################
# Automatically generated by qmake (2.01a) Mo. Apr 18 21:43:16 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += myclass.h
SOURCES += main.cpp myclass.cpp
