######################################################################
# Automatically generated by qmake (2.01a) Sa. Apr 16 13:19:06 2016
######################################################################

QT += gui core
greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += myclass.h
SOURCES += main.cpp myclass.cpp
