######################################################################
# Automatically generated by qmake (2.01a) Fr. Apr 15 20:50:30 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += testing01.cpp
