######################################################################
# Automatically generated by qmake (2.01a) Di. Jun 7 20:42:58 2016
######################################################################


QT += core gui

greaterThan(QT_MAJOR_VERSION, 4): QT += widgets


TEMPLATE = app
TARGET = SdiDialog
DEPENDPATH += .
INCLUDEPATH += .




# Input
HEADERS += sdiwindow.h
SOURCES += main.cpp sdiwindow.cpp

RESOURCES += \
    res.qrc

DISTFILES +=
