######################################################################
# Automatically generated by qmake (3.0) Mo Mai 2 13:37:20 2016
######################################################################

TEMPLATE = app
QT += widgets
TARGET = threading
INCLUDEPATH += .

# Input
HEADERS += textthread.h \
    textdevice.h
SOURCES += main01.cpp textthread.cpp \
    textdevice.cpp
